### ISSUE TITLE
change/edit the reward fee

### ISSUE THREAD

**Issue by SimJach** [near/core-contracts#126]
Where can we change/edit the reward fee after the pool is deployed?

**Comment by evgenykuzyakov** [comment]
You need to call `update_reward_fee_fraction` on the staking pool account from the owner's account.
For example, if your owner account ID is `alice.near` and the pool is `wonderland.poolv1.near` then you can call this to set fee to `5%`:
 
```
export NEAR_ENV=mainnet
near call --accountId=alice.near wonderland.poolv1.near update_reward_fee_fraction '{"reward_fee_fraction": {"numerator": 5, "denominator": 100}}'
