### ISSUE TITLE
Change owner_id/wallet for deployed Mainnet Staking Pool Smart Contract

### ISSUE THREAD

**Issue by SimJach** [near/core-contracts#127]
Could you please advise how to:
make the owner_id change for already delployed MainNet staking pool. I mean the pool was deplyed as follows as example:

near call poolv1.near create_staking_pool................ "owner_id":"aaa.near" .......................--account_id aaa.near ................

and now I want to change the "owner_id":"aaa.near" to "owner_id":"bbb.near" with full permissions and delete the wallet aaa.near then.

**Comment by kucharskim** [comment]
Quote from Evgeny Kuzyakov on Telegram:
> Since we're planning to do an upgrade (for secp) on the contract we can add this method

That would be awesome, if you add possibility to change `owner_id` on the contract, as we have a business need for that functionality at Chorus One. cc @adrianbrink

**Comment by adrianbrink** [comment]
I strongly upvote this feature request.

**Comment by bowenwang1996** [comment]
This can be already done with https://github.com/referencedev/staking-farm/

**Comment by kucharskim** [comment]
That link is to a new smart contract, right? How I can change existing owner on an existing pool, for example `chorusone.poolv1.near`?

**Comment by bowenwang1996** [comment]
> That link is to a new smart contract, right? How I can change existing owner on an existing pool, for example chorusone.poolv1.near?

Unfortunately you cannot

**Comment by kucharskim** [comment]
Then this bug report should not be closed, shouldn't it?

**Comment by qezz** [comment]
Hey! This feature could be very beneficial for me as well. It's worth re-opening it as a feature request, isn't it?

**Comment by janewang** [comment]
This will be addressed when upgrading to the new staking pool
https://github.com/referencedev/staking-farm/blob/master/staking-farm/src/owner.rs#L48
