### ISSUE TITLE
[feature request] command to show all users staked

### ISSUE THREAD

**Issue by htafolla** [near/core-contracts#18]
Currently there does not seem to be a way to see all users that have staked to the contract. This creates an issue when you need to unstake to upgrade the contract. For instance Stefano sent some NEAR to one of my contracts and I'm not sure how to unstake him.

**Comment by jimmy3dita** [comment]
You can't =)
However, you can change your validator public key, and the current (obsolete) staking pool will not generate any rewards - so I'm economically interested to re-stake asap.

**Comment by evgenykuzyakov** [comment]
You can look at the explorer to find all users who interacted with the contract.

**Comment by evgenykuzyakov** [comment]
Closed by #85
