### ISSUE TITLE
Staking pool contract should have `pause` method for owner

### ISSUE THREAD

**Issue by frol** [near/core-contracts#41]
When we do hard-forks, we ask validators who cannot be online during the hard fork to unstake, but there is no way for the owner to unstake all the stake.

It is also useful for maintenance purposes.

/cc @jimmy3dita @nearmax

**Comment by evgenykuzyakov** [comment]
It's not unstake-all, but more like `shutdown` or `pause` the pool. The owner can put the pool into a paused mode which will not restake until it resumed.

**Comment by frol** [comment]
Well, on  shutdown it should return the delegated funds in my opinion. Pause might be more appropriate.

**Comment by jimmy3dita** [comment]
We need the command `pause`, as some validators shut down their nodes but the pool was still trying to stake.
The `unstake-all` is very helpful but I see important adversarial risks
