### ISSUE TITLE
[staking_pool] Add list all delegators view call

### ISSUE THREAD

**Issue by ilblackdragon** [near/core-contracts#42]
Currently there is no way to view who are delegating to given staking pool.
Let's add `list_delegators` or similar method, that returns all users who have delegated with their number of shares.
This will allow to make explorers and other tools for delegation easier.

**Comment by evgenykuzyakov** [comment]
Right now we don't store `accountId` of the delegator, but instead storing the hash. So we'll need to add `AccountId` inside the record as well.
This also needs pagination which might break if a new account added or removed.
