### ISSUE TITLE
Initialization of Contracts is Vulnerable to Front-running

### ISSUE THREAD

**Issue by nearmax** [near/core-contracts#46]
Impact: High
Likelihood: Medium
Reported by a third-party.

**Description**

There are two actions required to deploy and initialize a contract. The first is the deployment of the code which involves uploading the contract byte code ( .wasm file). The second is the initialization function (e.g. new() or default() ), which sets the account state storage based on the code in the contract. The initialization action may be called from any account.

If these actions are not part of a single transaction, it is possible to front-run the initialization transaction.

When an attacker witnesses a transaction to deploy the contract they may wait for the execution of the transaction, then front-run the initialization transaction (i.e. the call to new() ) with their own parameters. Front-running of transactions in this scenario is trivial for any block producer as they may decide the order of the transactions inserted into a new block and may always create the following scenario:
1. Deployment transaction;
2. Malicious initialisation transaction;
3. Owner initialisation transaction.

In the case of contract, an attacker can front-run the call to new() . This will allow the attacker to set the , the   and the transfers to be enabled. The attacker may then transfer the entire balance of the contract to their personal account.

In the case of contract, an attacker can front-run the call to new() . This will allow the attacker to set the   parameter, gaining ownership of the contract. The contract is required to be initialised with an initial balance which cannot be attached to the call to new() as it is not payable. The attacker will therefore receive all staking rewards fees associated with the contract, as they may set the reward percentage to 100%. Therefore, the fees received from this initial balance will be rewarded to the new owner.

In the case of the contract, the front runner can here again front-run the new() transaction call. The attacker may also set the parameter which will allocate them the entire token supply.

**Recommendations**
Ensure there is adequate documentation in all cases to warn users against the dangers of using multiple trans- actions. When deploying new contracts, developers should always initialize contracts in the same transaction.

**Comment by evgenykuzyakov** [comment]
Using near-shell repl to initialize contract, e.g. https://github.com/near/initial-contracts/tree/master/multisig
Estimate 3

**Comment by mikedotexe** [comment]
Linking https://github.com/near/near-shell/issues/260

**Comment by ilblackdragon** [comment]
Can we enforce that new can only be called by predecessor==current_account? And do this in Rust sdk? @nearmax

**Comment by nearmax** [comment]
> Can we enforce that new can only be called by predecessor==current_account? And do this in Rust sdk? @nearmax

As @evgenykuzyakov  noted,  we cannot do that for the contracts created with a factory. Our current plan is to address it through the documentation.
