### ISSUE TITLE
Storage Fees Can Lead to a Denial-of-Service Condition

### ISSUE THREAD

**Issue by nearmax** [near/core-contracts#47]
Reported by a third-party.
Impact: Medium
Likelihood: Medium

**Description**
In the fungible-token contract, transferring tokens to a new account will insert a key value pair into the accounts map in FungibleToken . The key is a sha256 hash of the account id and a new Account object as the value. The Account object contains a Balance and another Map which is a key pair of a sha256 hash of an account id and a Balance .

This implies a large quantity of storage is required to create a single account. Accounts can be created from the transfer of a single token which may have negligible value depending on the usage. At the cost of the transaction gas and a single token, per account, the attacker can generate a large quantity of storage by creating numerous accounts. As a result the contract will face high storage fees.

Alternatively, an attacker can create numerous entries into the allowances map requiring only a single token to create practically infinite allowances. The result is similar in that a large quantity of storage will be used by the contract at the cost of the transaction gas, resulting in high storage fees for the contract.

Note that these accounts only need to have valid IDs (i.e. they do not need to actually exist on the Blockchain).

**Recommendations**
The mainnet gas price is currently set to 100, 000 yocto per gas which would make the cost ratio 1/(5 ∗ 104) implying this is still a cheap and feasible attack.
To mitigate this type of attack, the cost of creating a new account can be increased. This may occur by any of the following:
• The contract charging a fee for an account creation;
• The contract burning an additional quantity of gas when creating a new account;
• The contract only allowing insertions of new accounts that exist;
• The network increasing gas price charged;
• Reducing storage fee requirements (could have undesirable side effects).

**Comment by evgenykuzyakov** [comment]
Make every call payable and require to pay for the extra storage introduced, it will also refund the difference

**Comment by evgenykuzyakov** [comment]
Estimate 3

**Comment by fckt** [comment]
This also introduces an incentive to clear storage, which is nice!

**Comment by vgrichina** [comment]
@evgenykuzyakov  IMO this is quite suboptimal in terms of UX (e.g. if I understand correctly – no way to have limited access keys for these methods anymore), is there any way to do this using attached gas vs NEAR tokens?

**Comment by fckt** [comment]
Interesting.. But AKs are bounded to the account, so only "sender == receiver" Receipts are possible for AKs. Sender will always have enough balance to pay for storage. Also I don't see any scenario for AK for Fungible token.

**Comment by evgenykuzyakov** [comment]
Limited access keys will not be used directly. The wallet will have to sign this transaction instead to be more secure.

The escrow account can attach the balance when calling the token, so it works there. But I agree that this is somewhat suboptimal.
