### ISSUE TITLE
Allowance Front-Running

### ISSUE THREAD

**Issue by nearmax** [near/core-contracts#49]
Impact: Low
Likelihood: Low
Reported by a third-party.

**Description**
Front-running attacks [1, 2] involve users watching the blockchain for particular transactions and, upon observing such a transaction, submitting their own transactions to be executed before the original transaction.

Furthermore, front-running can simply be done by block producers by inserting their transaction before the original transaction when producing a block.

The front-running vulnerability exists in the set_allowance() function.
Consider the following scenario:
1. Alice approves Malory to spend 1000 tokens, by calling the set_allowance() function on the token contract;
2. Alice wants to reduce the allowance, from 1000 tokens to 500 tokens, and sends a new transaction to call the set_allowance() function, this time with allowance as 500 .
3. Malory watches the blockchain transaction pool and notices that Alice wants to decrease the allowance.
Malory proceeds with sending a transaction to spend the 1000 tokens, which if mined before Alice’s second transaction;
4. Alice’s second set_allowance() happens, effectively providing Malory with an additional allowance of 500 tokens;
5. Malory spends the additional 500 token. As a result, Malory spent 1500 tokens, when Alice wanted her to only spend 500 tokens.

**Recommendations**
Be aware of the front-running issues in set_allowance() and potentially add extended allowance functions which are not vulnerable to the front-running vulnerability. The functions increase_allowance() and decrease_allowance() may be used to prevent double spending
of the allowance, however decrease will still be vulnerable to front-running the amount to be decreased. A further method typically used to address this attack vector is to force users to change the allowance to 0 first, before updating it to the desired value (requires two separate transactions). See the safeApprove() function in OpenZeppelin’s SafeERC20 contract.

**Comment by evgenykuzyakov** [comment]
Switch to increase and decrease allowance.
- [ ] Update Spec
- [ ] both increase and decrease should be saturating to `u128::MAX` and `0`
- [ ] Remove `set_allowance`

Estimate 3.

**Comment by miohtama** [comment]
In practice, this is no issue, as Malory could spend those tokens **without** watching the blockchain. 

This is just an overbloated addon to ERC-20 because some security researchers wanted to make name for themselves.

I recommend NEAR does not copy this nonsense baggage from Ethereum world.
