### ISSUE TITLE
Terminate Vesting Deficit Includes Storage Fees

### ISSUE THREAD

**Issue by nearmax** [near/core-contracts#50]
**Description**
In the lockup contract, a vesting schedule is able to be terminated by the NEAR Foundation if a NEAR Foundation AccountId is provided, with the remaining unvested balance to be withdrawn by the NEAR foundation. If the contract does not have enough balance to cover the unvested amount, it assumes that the difference is in the staking pool and attempts to withdraw that.

The contract uses the minimum of the remaining unvested amount and get_account_balance() to determine how much can be withdrawn by the NEAR Foundation. However, due to the requirements to maintain a minimum balance for storage fees, get_account_balance() subtracts the MIN_BALANCE_FOR_STORAGE from the actual account balance.

It is possible to reach the case where all amounts have been withdrawn from the staking pool and there is insufficient account balance to cover the remaining unvested amount and MIN_BALANCE_FOR_STORAGE . This case can be reached by terminating a contract before any amounts have been vested.

As a result the NEAR Foundation will not be able to withdraw the entire unvested balance. The contract will be stuck in the TerminationStatus::ReadyToWithdraw status, and get_terminated_unvested_balance() will be equal to the MIN_BALANCE_FOR_STORAGE .

To unlock the contract and withdraw the remaining balance there must be a deposit of MIN_BALANCE_FOR_STORAGE made to the contract.

**Recommendations**
Ensure that the development team is aware of this edge case which may require transferring an additional 35 NEAR to finalise termination of the contract.

**Comment by evgenykuzyakov** [comment]
Update docs. Explain that during termination before cliff, the foundation will not be able to withdraw all tokens, but everything except for `MIN_BALANCE_FOR_STORAGE` which is set 35 NEAR tokens. Adjusted for some rewards from staking.
Estimate 1.
