### ISSUE TITLE
Allowance Can Be Set Larger Than Balance

### ISSUE THREAD

**Issue by nearmax** [near/core-contracts#57]
Informational
Reported by a third party.

**Description**
In the fungible-token contract, FungibleToken::set_allowance() takes an allowance as input which
gives another account the ability to spend these funds on their behalf.

There are no checks to ensure the current account balance of the sender is greater than the allowance. This may lead a user to believe that they have an allowance larger than what is actually available.

**Recommendations**
This is the same behaviour as the Ethereum ERC20 token specification. As such no action is required other than the developers be aware of this behaviour.

**Comment by evgenykuzyakov** [comment]
Actually we don't want to enforce it. A scenario, where the owner give unlimited allowance to the exchange and later can actively trade the given token with the exchange without having to increase the allowance after every trade.
