### ISSUE TITLE
Insufficient stake can cause staking pool to be internally inconsistent

### ISSUE THREAD

**Issue by bowenwang1996** [near/core-contracts#77]
Since https://github.com/nearprotocol/nearcore/pull/2805, if someone tries to stake less than the minimum threshold, the staking transaction will fail. This causes issues with the staking pool. For example, when some large delegator wants to withdraw all their stake, the rest of the stake left in the staking pool might be less than the minimum threshold, in which cause the unstaking will fail because it tries to restake with what is left and this causes the contract to enter an inconsistent state because from the contract perspective, unstaking succeeds. A similar issue exists if someone delegates a small amount of tokens to the pool such that the total stake in the pool is below the minimum threshold. We should check the result of the staking action to prevent the contract from entering such inconsistent state.

**Comment by evgenykuzyakov** [comment]
Let's say the account has active stake of Y, it tries to stake X, which smaller than the threshold T.  

There are a few ways to address it:
1. Address it on nearcore side. Change result of the action to success, but instead unstake everything. Issues: it maybe confusing to the user, and it maybe not the intent.
2. Address it on the staking pool side. Add a callback to each re-staking action to restake 0, in case the staking action fails.
3. A hack on the staking pool side. Issue 2 promises, the first is to stake 0, the second is to stake X. Assuming they both executed in the same block (in order), only the 2nd one will be reported to the epoch manager. 

We can also expose minimum threshold, but it doesn't save us if the staking action arrives to the next epoch.

Overall it seems the contract has to be updated to address this issue.

**Comment by bowenwang1996** [comment]
It would be nice to avoid change to nearcore as we now have to make things backward compatible.

> Address it on the staking pool side. Add a callback to each re-staking action to restake 0, in case the staking action fails.

Looks promising, but doesn't restake 0 still break the contract internals? Or does that mean we unstake for every delegator?

> A hack on the staking pool side. Issue 2 promises, the first is to stake 0, the second is to stake X. Assuming they both executed in the same block (in order), only the 2nd one will be reported to the epoch manager.

Same concern as above (whether the contract will be consistent after this operation)

**Comment by evgenykuzyakov** [comment]
Anytime the contract can be kicked out due to extra stakes from other validations, so it's fine to have less locked amount that the intended amount. But it's an issue to think the contract unstaked when it didn't. Because withdrawal actions will start to fail.

**Comment by bowenwang1996** [comment]
I see. Seems like option 2 makes the most sense.
